### PR TITLE
Make NGINX controller image configurable and update to the latest image

### LINKED ISSUE #8: Link to nginx-ingress-controller out of date.  No longer uses quay
The latest releases of nginx-ingress-controller no longer use quay to store the image.  They have a different link to the image.

The last release to use quay is version 0.33.0. This isnt too many releases behind but this repo should be updated to make sure it can stay up to date.

Can be solved two ways
* Can the url of the image to what the latest releases use
* Expose the link to the image as an input and use that when specifying the image when creating the resource.
    - This would probably be the best approach as it would still allow users who would like to use the older versions

You can see the last images of quay to be uploaded here:
https://quay.io/repository/kubernetes-ingress-controller/nginx-ingress-controller?tab=tags

I would be happy to create a pull request for this.  Please let me know.

### PR DESCRIPTION
**Pull request by bwinterton**
Fixes #8

### CODE REVIEW

**Review by dannyrandall — DISMISSED** [review]
lgtm

**Comment by johankritzinger** [comment]
The default value for nginx_ingress_controller_version does not work with the app.kubernetes.io/version label as currently defined

**Comment by bwinterton** [comment]
I will double check this on my end. Though, I have followed the exact image string that the Kubernetes team has used in the deployment documents they provide.

https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.35.0/deploy/static/provider/aws/deploy.yaml

**Comment by johankritzinger** [comment]
The default value for version is set to `v0.35.0@sha256:fc4979d8b8443a831c9789b5155cded454cb7de737a8b727bc2ba0106d2eae8b` which is too long, and the @ and : is not accepted in a label.
This can be fixed by doing some sanity checking e.g on line 211 in nginx.tf, or being less clever with the default value :)

**Comment by johankritzinger** [comment]
PS.  I don't have rights to create branches, otherwise I'd have done a PR into your branch....  Thanks for your work on this.

**Comment by bwinterton** [comment]
I see what you're saying now. You're right, I had forgotten our use of the version in the metadata. I've updated that in this pull and am double checking that now.

**Comment by bwinterton** [comment]
Confirmed the new commit fixes this issue. 

I've also changed the `nginx_ingress_controller_version` variable to be `nginx_ingress_controller_image_tag` to better fit with the actual usage of the variable now. Since we will allow users to use any arbitrary image here, it's best to not make assumptions about how the tags match up with versions and just allow users to define the full image tag. 

The metadata will now strip any added digest from the tag to keep the length low and the metadata more readable.

**Review by johankritzinger — DISMISSED** [review]
That should fix the issue I found

**Review by dannyrandall — DISMISSED** [review]

**Review by dannyrandall — APPROVED** [review]

**Pull request merged**
